# -*- coding: utf-8 -*-
"""Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15w9QiMk0ybWvyyGAQVB17lSdPtx7OeLV
"""

# ==========================================
# DATA CLEANING & VISUALIZATION PROJECT
# Titanic Dataset Analysis
# ==========================================

# STEP 1 — Import Libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# ==========================================
# STEP 2 — Load Dataset
# ==========================================

url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"

df = pd.read_csv(url)

# Display first 5 rows
print("FIRST 5 ROWS OF DATASET")
print(df.head())

# ==========================================
# STEP 3 — Dataset Information
# ==========================================

print("\nDATASET INFORMATION")
print(df.info())

print("\nSTATISTICAL SUMMARY")
print(df.describe())

# ==========================================
# STEP 4 — Check Missing Values
# ==========================================

print("\nMISSING VALUES")
print(df.isnull().sum())

# ==========================================
# STEP 5 — Handle Missing Values
# ==========================================

# Fill missing Age values with mean
df['Age'] = df['Age'].fillna(df['Age'].mean())

# Fill missing Embarked values with mode
df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])

# Drop Cabin column due to too many missing values
df.drop('Cabin', axis=1, inplace=True)

print("\nMISSING VALUES AFTER CLEANING")
print(df.isnull().sum())

# ==========================================
# STEP 6 — Check and Remove Duplicates
# ==========================================

print("\nDUPLICATE ROWS")
print(df.duplicated().sum())

# Remove duplicates
df.drop_duplicates(inplace=True)

print("\nDUPLICATES REMOVED")

# ==========================================
# STEP 7 — Detect Outliers Using Boxplot
# ==========================================

plt.figure(figsize=(8,5))
sns.boxplot(x=df['Fare'])
plt.title("Boxplot of Fare")
plt.show()

# ==========================================
# STEP 8 — Remove Outliers Using IQR Method
# ==========================================

Q1 = df['Fare'].quantile(0.25)
Q3 = df['Fare'].quantile(0.75)

IQR = Q3 - Q1

lower_limit = Q1 - 1.5 * IQR
upper_limit = Q3 + 1.5 * IQR

df = df[(df['Fare'] >= lower_limit) & (df['Fare'] <= upper_limit)]

print("\nOUTLIERS REMOVED")

# ==========================================
# STEP 9 — Data Visualization
# ==========================================

# -------------------------------
# 1. Histogram
# -------------------------------

plt.figure(figsize=(8,5))
df['Age'].hist(bins=20)
plt.title("Age Distribution")
plt.xlabel("Age")
plt.ylabel("Count")
plt.show()

# -------------------------------
# 2. Survival Count Plot
# -------------------------------

plt.figure(figsize=(6,5))
sns.countplot(x='Survived', data=df)
plt.title("Survival Count")
plt.show()

# -------------------------------
# 3. Correlation Heatmap
# -------------------------------

plt.figure(figsize=(10,6))

sns.heatmap(
    df.corr(numeric_only=True),
    annot=True,
    cmap='coolwarm'
)

plt.title("Correlation Heatmap")
plt.show()

# -------------------------------
# 4. Scatter Plot
# -------------------------------

plt.figure(figsize=(8,5))

sns.scatterplot(
    x='Age',
    y='Fare',
    data=df
)

plt.title("Age vs Fare")
plt.show()

# -------------------------------
# 5. Bar Plot
# -------------------------------

plt.figure(figsize=(8,5))

sns.barplot(
    x='Pclass',
    y='Fare',
    data=df
)

plt.title("Passenger Class vs Fare")
plt.show()

# ==========================================
# STEP 10 — Save Cleaned Dataset
# ==========================================

df.to_csv("cleaned_titanic.csv", index=False)

print("\nCLEANED DATASET SAVED SUCCESSFULLY")

# ==========================================
# STEP 11 — Insights
# ==========================================

print("\nPROJECT INSIGHTS")

print("1. Missing values were successfully handled.")
print("2. Duplicate rows were removed.")
print("3. Outliers in Fare column were removed.")
print("4. Most passengers were aged between 20 and 40.")
print("5. Higher-class passengers paid higher fares.")
print("6. Correlation heatmap shows relationships between features.")

# ==========================================
# END OF PROJECT
# ==========================================